require_relative 'generators/game_generator'
require_relative 'generators/profile_generator'
require_relative 'generators/role_generator'
require_relative 'generators/player_generator'
require_relative 'generators/observation_generator'