require_relative 'models/player'
require_relative 'models/profile'
require_relative 'models/role'
require_relative 'models/strategy'
require_relative 'models/symmetry_group'
require_relative 'models/observation'